services:
  - type: web
    name: lokiplus-api
    env: python
    region: ohio  # Choose a region close to your users
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: SUPABASE_URL
        value: https://nusligglyvgsmuvauyce.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: PYTHONPATH
        value: src
    healthCheckPath: /health
    healthCheckTimeout: 100
    autoDeploy: true
    numInstances: 1
    domains:
      - lokiplus-api.onrender.com 