services:
  - type: web
    name: lokiplus-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: PYTHONPATH
        value: .
    healthCheckPath: /health
    autoDeploy: true 